/**
 * Tle API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TleData model module.
 * @module model/TleData
 * @version 0.0.1
 */
class TleData {
    /**
     * Constructs a new <code>TleData</code>.
     * @alias module:model/TleData
     */
    constructor() { 
        
        TleData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TleData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TleData} obj Optional instance to populate.
     * @return {module:model/TleData} The populated <code>TleData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TleData();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('line1')) {
                obj['line1'] = ApiClient.convertToType(data['line1'], 'String');
            }
            if (data.hasOwnProperty('line2')) {
                obj['line2'] = ApiClient.convertToType(data['line2'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
TleData.prototype['name'] = undefined;

/**
 * @member {String} line1
 */
TleData.prototype['line1'] = undefined;

/**
 * @member {String} line2
 */
TleData.prototype['line2'] = undefined;






export default TleData;

