/**
 * Tle API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TleToCorridorRes model module.
 * @module model/TleToCorridorRes
 * @version 0.0.1
 */
class TleToCorridorRes {
    /**
     * Constructs a new <code>TleToCorridorRes</code>.
     * @alias module:model/TleToCorridorRes
     */
    constructor() { 
        
        TleToCorridorRes.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TleToCorridorRes</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TleToCorridorRes} obj Optional instance to populate.
     * @return {module:model/TleToCorridorRes} The populated <code>TleToCorridorRes</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TleToCorridorRes();

            if (data.hasOwnProperty('corridor')) {
                obj['corridor'] = ApiClient.convertToType(data['corridor'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} corridor
 */
TleToCorridorRes.prototype['corridor'] = undefined;






export default TleToCorridorRes;

