/**
 * Tle API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TleData from './TleData';

/**
 * The TleToOrbitReq model module.
 * @module model/TleToOrbitReq
 * @version 0.0.1
 */
class TleToOrbitReq {
    /**
     * Constructs a new <code>TleToOrbitReq</code>.
     * @alias module:model/TleToOrbitReq
     */
    constructor() { 
        
        TleToOrbitReq.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TleToOrbitReq</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TleToOrbitReq} obj Optional instance to populate.
     * @return {module:model/TleToOrbitReq} The populated <code>TleToOrbitReq</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TleToOrbitReq();

            if (data.hasOwnProperty('tleData')) {
                obj['tleData'] = TleData.constructFromObject(data['tleData']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/TleData} tleData
 */
TleToOrbitReq.prototype['tleData'] = undefined;






export default TleToOrbitReq;

