/**
 * Tle API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import TleData from './model/TleData';
import TleDecodeReq from './model/TleDecodeReq';
import TleDecodeRes from './model/TleDecodeRes';
import TleToOrbitReq from './model/TleToOrbitReq';
import TleToOrbitRes from './model/TleToOrbitRes';
import TleApi from './api/TleApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var TleApi = require('index'); // See note below*.
* var xxxSvc = new TleApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new TleApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new TleApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new TleApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.0.1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The TleData model constructor.
     * @property {module:model/TleData}
     */
    TleData,

    /**
     * The TleDecodeReq model constructor.
     * @property {module:model/TleDecodeReq}
     */
    TleDecodeReq,

    /**
     * The TleDecodeRes model constructor.
     * @property {module:model/TleDecodeRes}
     */
    TleDecodeRes,

    /**
     * The TleToOrbitReq model constructor.
     * @property {module:model/TleToOrbitReq}
     */
    TleToOrbitReq,

    /**
     * The TleToOrbitRes model constructor.
     * @property {module:model/TleToOrbitRes}
     */
    TleToOrbitRes,

    /**
    * The TleApi service constructor.
    * @property {module:api/TleApi}
    */
    TleApi
};
